<?php

namespace App\Models;

use App\Observers\CategoryObserver;
use App\Observers\PlaceObserver;
use App\Traits\HasCategoryTranslationUpdate;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\HasIcon;

class Category extends Model implements TranslatableContract
{
    use SoftDeletes, Translatable, HasCategoryTranslationUpdate , HasIcon;

    public $inPermission = true;
    public array $translatedAttributes = ['name', 'notes'];
    protected $with = ['translations'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(CategoryObserver::class);
    }

    protected $dates = [
        'deleted_at',
    ];

    protected $fillable = [
        'icon', 'parent_id', 'order_id',
    ];

    public static function allParents()
    {
        return Category::whereNull('parent_id')->get();
    }

    public function childes()
    {
        return $this->hasMany(self::class, 'parent_id');
    }

    public function parent()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }

}
