<?php

namespace App\Models;

use App\Observers\CategoryObserver;
use App\Traits\HasCategoryTranslationUpdate;
use App\Traits\HasIcon;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CategoryOfSwalef extends Model implements TranslatableContract
{
    use HasFactory,
        Translatable,
        HasCategoryTranslationUpdate,
        HasIcon;

    protected $fillable = [
        'icon', 'parent_id', 'order_id',
    ];

    public $inPermission = true;

    public array $translatedAttributes = ['name', 'notes'];

    protected $with = ['translations'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(CategoryObserver::class);
    }

    protected $dates = [
        'deleted_at',
    ];

    public static function allParents()
    {
        return CategoryOfSwalef::whereNull('parent_id')->get();
    }

    public function childes()
    {
        return $this->hasMany(self::class, 'parent_id');
    }

    public function parent()
    {
        return $this->belongsTo(self::class, 'parent_id');
    }
}
