<?php

namespace App\Models;

use App\Observers\NameObserver;
use App\Traits\HasNameTranslationUpdate;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class City extends Model implements TranslatableContract
{
    use HasFactory, SoftDeletes, Translatable, HasNameTranslationUpdate;

    public $inPermission = true;
    public $translatedAttributes = ['name'];
    protected $with = ['translations'];

    protected $dates = [
        'deleted_at',
    ];

    protected $fillable = [
        'name', 'region_id',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(NameObserver::class);
    }

    public function region()
    {
        return $this->belongsTo(Region::class, 'region_id', 'id');
    }
}
