<?php

namespace App\Models;

use App\Observers\PlaceObserver;
use App\Traits\HasImage;
use App\Traits\HasPlaceTranslationUpdate;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Event extends Model implements TranslatableContract, HasMedia
{
    use HasFactory, SoftDeletes, HasImage, Translatable, HasPlaceTranslationUpdate, InteractsWithMedia;

    public array $translatedAttributes = ['title', 'description'];
    protected $with = ['translations'];
    public const TYPE_EVENT = 'Event';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(PlaceObserver::class);
    }

    static $types = [
        'banner' => 'Banner',
        'top_bar' => 'Top Bar',
    ];

    protected $fillable = [
        'title', 'description', 'categories', 'image', 'type', 'address', 'link', 'lat', 'long', 'active',
        'featured', 'related', 'facebook', 'x', 'whatsapp', 'instagram', 'website', 'visited', 'views_num',
        'city_id', 'region_id', 'date_from', 'date_to', 'ticket_link', 'display_type', 'slug','video_url',
        'ownership_proof_file', 'user_id', 'rejected_reason', 'status', 'added_by_user', 'order_id',
    ];

    public $appends = [
        'address_type',
    ];

    public function getAddressTypeAttribute()
    {
        return $this->attributes['type'] ?? null;
    }

    public function getTypeAttribute()
    {
        return 'event';
    }

    public function region()
    {
        return $this->belongsTo(Region::class);
    }

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class)->withDefault();
    }

    public function galleries()
    {
        return $this->hasMany(Gallery::class, "parent_id")->where('type', '=', 'events');
    }

    public function getLatAttribute()
    {
        return $this->attributes['lat'] ? round($this->attributes['lat'], 10) : 0;
    }

    public function getLongAttribute()
    {
        return $this->attributes['long'] ? round($this->attributes['long'], 10) : 0;
    }

    public function ceo()
    {
        return $this->hasOne(Ceo::class, "parent_id")->where('type', '=', 'events');
    }

    public function ratings()
    {
        return $this->hasMany(Rate::class, 'parent_id')->where('type', '=', 'event')->orderBy('id', 'desc');
    }

    public function getRateAttribute()
    {
        return $this->ratings()->count() ? round($this->ratings()->sum('rate') / $this->ratings()->count(), 1) : 0;
    }

    public function getReviewAttribute()
    {
        return $this->ratings()->count() ? $this->ratings()->count() : 0;
    }

    public function favorites()
    {
        return $this->morphMany(Favorite::class, 'favoritable');
    }

    public function getOwnershipProofFileAttribute()
    {
        if ($this->attributes['ownership_proof_file']) {
            if (file_exists('uploads/' . $this->attributes['ownership_proof_file'])) {
                return 'uploads/' . $this->attributes['ownership_proof_file'];
            }
        }
        return 'front_assets/imgs/zad1.jpg';
    }

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('image')
            ->singleFile()
            ->acceptsMimeTypes(['image/jpeg', 'image/png', 'image/jpg', 'image/gif', 'image/svg', 'image/webp'])
            ->useDisk('media');
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('small')
            ->width(250)
            ->height(250)
            ->sharpen(10)
            ->nonQueued()
            ->performOnCollections('image');

        $this->addMediaConversion('medium')
            ->width(500)
            ->height(500)
            ->sharpen(10)
            ->nonQueued()
            ->performOnCollections('image');
    }
}
