<?php

namespace App\Models;

use App\Observers\FeatureObserver;
use App\Observers\NameObserver;
use App\Traits\HasFeatureTranslationUpdate;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Feature extends Model implements TranslatableContract
{
    use HasFactory, Translatable, HasFeatureTranslationUpdate;

    protected $guarded = [];
    public $translatedAttributes = ['name', 'description'];
    protected $with = ['translations'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(FeatureObserver::class);
    }

    public function caravan()
    {
        return $this->belongsToMany(Caravan::class);
    }
}
