<?php

namespace App\Models;

use App\Observers\CategoryObserver;
use App\Traits\HasCategoryTranslationUpdate;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Traits\HasIcon;

class FoodCategoryOfZad extends Model implements TranslatableContract
{
    use HasFactory, Translatable, HasCategoryTranslationUpdate, HasIcon;

    protected $fillable = [
        'icon', 'parent_id', 'order_id',
    ];
    public array $translatedAttributes = ['name', 'notes'];
    protected $with = ['translations'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(CategoryObserver::class);
    }

    public $inPermission = true;

    protected $dates = [
        'deleted_at',
    ];

    public static function allParents()
    {
        return CategoryOfZad::whereNull('parent_id')->get();
    }

    public function childes()
    {
        return $this->hasMany(self::class, 'parent_id');
    }

    public function parent()
    {
        return $this->belongsTo(CategoryOfZad::class, 'parent_id')->withDefault();
    }

    public function zadElgadels()
    {
        return $this->belongsToMany(ZadElgadel::class, 'food_category_zad_elgadels', 'food_category_id', 'zad_elgadel_id');
    }
}
