<?php

namespace App\Models;

use App\Observers\OfferObserver;
use App\Traits\HasOfferTranslationUpdate;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;

class Offer extends Model
{
    use HasFactory , Translatable , SoftDeletes , HasOfferTranslationUpdate;

    protected $fillable = ['image' , 'to' , 'from' , 'discount' , 'menu_id', 'order_id'];
    public $translatedAttributes = ['title', 'description'];
    protected $table = 'offers';
    protected $with = ['translations'];
    protected $translationForeignKey = 'offer_id';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(OfferObserver::class);
    }

    public function menu()
    {
        return $this->belongsTo(Menu::class , 'menu_id');
    }
}
