<?php

namespace App\Models;

use App\Observers\PlaceObserver;
use App\Traits\HasImage;
use App\Traits\HasPlaceTranslationUpdate;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Place extends Model implements TranslatableContract, HasMedia
{
    use SoftDeletes, HasFactory, HasImage, Translatable, HasPlaceTranslationUpdate, InteractsWithMedia;

    protected $guarded = [];
    public array $translatedAttributes = ['title', 'description'];
    protected $with = ['translations'];
    public const TYPE_PLACE = 'Place';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(PlaceObserver::class);
    }

    protected $casts = [
        // 'seasons' => 'array',
        'key_words' => 'array',
        'categories' => 'array',
        'lat' => 'float',
        'long' => 'float',
        'user_id' => 'int',
        'related_places' => 'array',
        'near_stores' => 'array',
        'featured' => 'boolean',
        'visited' => 'boolean',
    ];

    public $appends = [
        'rate',
        'review',
        'type',
        // 'distance'
    ];

    public function getTypeAttribute()
    {
        return 'place';
    }

    // public function getDistanceAttribute()
    // {
    //     if ((request('lat1')) && (request('long1'))) {
    //         return distance($this->attributes['lat'], $this->attributes['long'], request('lat1'), request('long1'), "K");
    //     } else {
    //         return null;
    //     }
    // }

    public function getSeasonsAttribute()
    {
        return $this->attributes['seasons'] ? (!is_array($this->attributes['seasons']) ? explode(',', $this->attributes['seasons']) : $this->attributes['seasons']) : [];
    }

    public function getSeasonsTraAttribute()
    {
        $seasons = $this->seasons;
        
        if (empty($seasons) || !is_array($seasons)) {
            return [];
        }

        $seasonMapping = [
            'موسم الربيع' => 'spring',
            'موسم الصيف' => 'summer',
            'موسم الخريف' => 'fall',
            'موسم الشتاء' => 'winter',
            'طوال العام' => 'all_year',
            'spring' => 'spring',
            'summer' => 'summer',
            'fall' => 'fall',
            'winter' => 'winter',
            'all_year' => 'all_year',
        ];

        $locale = request()->header('Locale') ?? request()->header('locale') ?? app()->getLocale();
        
        return collect($seasons)->map(function ($season) use ($seasonMapping, $locale) {
            $key = $seasonMapping[$season] ?? $season;
            $translationKey = $key === 'all_year' ? 'dashboard.all_year' : "dashboard.{$key}_season";
            
            return trans($translationKey, [], $locale);
        })->toArray();
    }

    public function getCategoriesAttribute()
    {
        return $this->attributes['categories'] ? json_decode($this->attributes['categories'], true) : [];
    }

    public function allCategories()
    {
        return \App\Models\Category::whereIn('id',$this->categories)->get();
    }

    public function region()
    {
        return $this->belongsTo(Region::class);
    }

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class)->withDefault();
    }

    public function galleries()
    {
        return $this->hasMany(Gallery::class, "parent_id")->where('type', '=', 'places');
    }

    public function ratings()
    {
        return $this->hasMany(Rate::class, 'parent_id')->where('type', '=', 'place')->orderBy('id', 'desc');
    }

    public function ceo()
    {
        return $this->hasOne(Ceo::class, "parent_id")->where('type', '=', 'places');
    }

    public function getRateAttribute()
    {
        return $this->ratings->count() ? round($this->ratings->sum('rate') / $this->ratings->count(), 1) : 0;
    }

    public function getReviewAttribute()
    {
        return $this->ratings->count() ? $this->ratings->count() : 0;
    }

    public function price()
    {
        return $this->belongsTo(Price::class);
    }

    public function getLatAttribute()
    {
        return $this->attributes['lat'] ? round($this->attributes['lat'], 10) : 0;
    }

    public function getLongAttribute()
    {
        return $this->attributes['long'] ? round($this->attributes['long'], 10) : 0;
    }

    public function favorites()
    {
        return $this->morphMany(Favorite::class, 'favoritable');
    }

    public function getOwnershipProofFileAttribute()
    {
        if ($this->attributes['ownership_proof_file']) {
            if (file_exists('uploads/' . $this->attributes['ownership_proof_file'])) {
                return 'uploads/' . $this->attributes['ownership_proof_file'];
            }
        }
        return 'front_assets/imgs/zad1.jpg';
    }

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('image')
            ->singleFile()
            ->acceptsMimeTypes(['image/jpeg', 'image/png', 'image/jpg', 'image/gif', 'image/svg', 'image/webp'])
            ->useDisk('media');
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('small')
            ->width(250)
            ->height(250)
            ->sharpen(10)
            ->nonQueued()
            ->performOnCollections('image');

        $this->addMediaConversion('medium')
            ->width(500)
            ->height(500)
            ->sharpen(10)
            ->nonQueued()
            ->performOnCollections('image');
    }
}
