<?php

namespace App\Models;

use App\Observers\NameObserver;
use App\Traits\HasNameTranslationUpdate;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Price extends Model implements TranslatableContract
{
    use HasFactory, Translatable, HasNameTranslationUpdate;

    protected $guarded = [];
    public array $translatedAttributes = ['name'];
    protected $with = ['translations'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(NameObserver::class);
    }
}
