<?php

namespace App\Models;

use App\Observers\NameObserver;
use App\Traits\HasNameTranslationUpdate;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Region extends Model implements TranslatableContract
{
    use HasFactory, SoftDeletes, Translatable, HasNameTranslationUpdate;

    protected $guarded = [];
    public $inPermission = true;
    public array $translatedAttributes = ['name'];
    protected $with = ['translations'];

    protected $dates = [
        'deleted_at',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(NameObserver::class);
    }

    public function cities()
    {
        return $this->hasMany(City::class);
    }
}
