<?php

namespace App\Models;

use App\Observers\PlaceObserver;
use App\Observers\SwalefObserver;
use App\Traits\HasImage;
use App\Traits\HasPlaceTranslationUpdate;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class Swalef extends Model implements TranslatableContract, HasMedia
{
    use HasFactory, HasImage, Translatable, HasPlaceTranslationUpdate, InteractsWithMedia;

    protected $casts = [
        'categories' => 'array',
        'show_in_home' => 'boolean',
    ];

    protected $guarded = ['ar' , 'en'];

    public array $translatedAttributes = [
        'title', 'description', 'content', 'timePeriod', 'location', 'storyImportance',
        'relevanceToPresent', 'source', 'audioStoryTitle',
    ];

    protected $with = ['translations'];
    public const TYPE_SWALEF = 'Swalef';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(SwalefObserver::class);
    }

    const TYPES = [
        'شعر' => 'text',
        'مثل عربي' => 'text',
        'قصه' => 'textarea',
        'ملف' => 'file'
    ];

    public $appends = [
        'rate',
        'review',
        'type'
    ];

    public function getTypeAttribute()
    {
        return 'swalef';
    }

    public function ratings()
    {
        return $this->hasMany(Rate::class, 'parent_id')->where('type', '=', 'swalef')->orderBy('id', 'desc');
    }

    public function getRateAttribute()
    {
        return $this->ratings()->count() ? round($this->ratings()->sum('rate') / $this->ratings()->count(), 1) : 0;
    }

    public function getReviewAttribute()
    {
        return $this->ratings()->count() ? $this->ratings()->count() : 0;
    }

    public function favorites()
    {
        return $this->morphMany(Favorite::class, 'favoritable');
    }

    public function getCategoriesAttribute()
    {
        return isset($this->attributes['categories']) ? json_decode($this->attributes['categories'], true) : [];
    }

    public function allCategories()
    {
        return \App\Models\Category::whereIn('id',$this->categories)->get();
    }

    public function galleries()
    {
        return $this->hasMany(Gallery::class, "parent_id")->where('type', '=', 'swalefs');
    }

    public function user()
    {
        return $this->belongsTo(User::class)->withDefault();
    }

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('image')
            ->singleFile()
            ->acceptsMimeTypes(['image/jpeg', 'image/png', 'image/jpg', 'image/gif', 'image/svg', 'image/webp'])
            ->useDisk('media');
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('small')
            ->width(250)
            ->height(250)
            ->sharpen(10)
            ->nonQueued()
            ->performOnCollections('image');

        $this->addMediaConversion('medium')
            ->width(500)
            ->height(500)
            ->sharpen(10)
            ->nonQueued()
            ->performOnCollections('image');
    }
}
