<?php

namespace App\Models;

use App\Observers\PlaceObserver;
use App\Traits\HasImage;
use App\Traits\HasPlaceTranslationUpdate;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class ZadElgadel extends Model implements TranslatableContract, HasMedia
{
    use SoftDeletes, HasFactory, HasImage, Translatable, HasPlaceTranslationUpdate, InteractsWithMedia;

    public array $translatedAttributes = ['title', 'description'];
    protected $with = ['translations'];
    public const TYPE_ZAD_ELGADEL = 'Zad_elgadel';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::observe(PlaceObserver::class);
    }

    protected $guarded = [];

    protected $casts = [
        'categories' => 'array',
        'food_categories' => 'array',
        'related_stores' => 'array',
        'near_places' => 'array',
        'featured' => 'boolean',
        'visited' => 'boolean',
    ];

    public $appends = [
        'rate',
        'review',
        'type'
    ];

    public function getTypeAttribute()
    {
        return 'zad';
    }

    public function allCategories()
    {
        return \App\Models\CategoryOfZad::whereIn('id',$this->categories ?? [])->get();
    }

    public function allFoodCategories()
    {
        return \App\Models\FoodCategoryOfZad::whereIn('id',$this->food_categories ?? [])->get();
    }

    public function region()
    {
        return $this->belongsTo(Region::class);
    }

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class)->withDefault();
    }

    public function category()
    {
        return $this->belongsTo(CategoryOfStore::class);
    }

    public function ceo()
    {
        return $this->hasOne(Ceo::class, "parent_id")->where('type', '=', 'zad_elgadels');
    }

    public function ratings()
    {
        return $this->hasMany(Rate::class, 'parent_id')->where('type', '=', 'zad')->orderBy('id', 'desc');
    }

    public function getRateAttribute()
    {
        return $this->ratings()->count() ? round($this->ratings()->sum('rate') / $this->ratings()->count(), 1) : 0;
    }

    public function getReviewAttribute()
    {
        return $this->ratings()->count() ? $this->ratings()->count() : 0;
    }

    public function getLatAttribute()
    {
        return $this->attributes['lat'] ? round($this->attributes['lat'], 10) : 0;
    }

    public function getLongAttribute()
    {
        return $this->attributes['long'] ? round($this->attributes['long'], 10) : 0;
    }

    public function galleries()
    {
        return $this->hasMany(Gallery::class, "parent_id")->where('type', '=', 'zad_elgadels');
    }

    public function getMenuFileAttribute()
    {
        if ($this->attributes['menu_file']) {
            if (file_exists('uploads/' . $this->attributes['menu_file'])) {
                return 'uploads/' . $this->attributes['menu_file'];
            }
        }
        return 'front_assets/imgs/zad1.jpg';
    }

    public function foodCategories()
    {
        return $this->belongsToMany(FoodCategoryOfZad::class, 'food_category_zad_elgadels', 'zad_elgadel_id', 'food_category_id');
    }

    public function categories()
    {
        return $this->belongsToMany(CategoryOfZad::class, 'category_zad_elgadels', 'zad_elgadel_id', 'category_id');
    }

    public function favorites()
    {
        return $this->morphMany(Favorite::class, 'favoritable');
    }

    public function getOwnershipProofFileAttribute()
    {
        if ($this->attributes['ownership_proof_file']) {
            if (file_exists('uploads/' . $this->attributes['ownership_proof_file'])) {
                return 'uploads/' . $this->attributes['ownership_proof_file'];
            }
        }
        return 'front_assets/imgs/zad1.jpg';
    }

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('image')
            ->singleFile()
            ->acceptsMimeTypes(['image/jpeg', 'image/png', 'image/jpg', 'image/gif', 'image/svg', 'image/webp'])
            ->useDisk('media');
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('small')
            ->width(250)
            ->height(250)
            ->sharpen(10)
            ->nonQueued()
            ->performOnCollections('image');

        $this->addMediaConversion('medium')
            ->width(500)
            ->height(500)
            ->sharpen(10)
            ->nonQueued()
            ->performOnCollections('image');
    }
}
